# bmcodexbot/utils_faktur.py
import os
import math
from fpdf import FPDF
from datetime import datetime, timedelta

class PDF(FPDF):
    def header(self):
        if os.path.exists('logo_invoice.png'):
            self.image('logo_invoice.png', 10, 8, 25)
        self.set_font('Arial', 'B', 14)
        self.cell(0, 5, 'JASA CLEAR VIRUS', 0, 1, 'R')
        self.ln(15) 

    def footer(self):
        self.set_y(-30) 
        self.set_font('Arial', 'B', 10)
        self.cell(0, 5, 'CLEAR VIRUS', 0, 1, 'C')
        self.set_font('Arial', '', 9)
        self.cell(0, 4, 'Kota Semarang', 0, 1, 'C')
        self.cell(0, 4, 'clearv1rusbybm@gmail.com | 0812-3189-8181', 0, 1, 'C')
        self.cell(0, 4, 'www.clearvirusbybm.com', 0, 1, 'C')
        self.set_y(-10)
        self.set_font('Arial', 'I', 8)
        self.cell(0, 5, 'Generated by Clear Virus', 0, 0, 'C')

def format_currency(amount):
    try:
        val = int(amount) if amount % 1 == 0 else amount
        return f"Rp {val:,.0f}".replace(',', '.') + ",00"
    except:
        return str(amount)

# PERBAIKAN: Menyesuaikan parameter dengan modules/faktur.py
def generate_faktur(user_id, nama_klien, email_klien, no_hp, deskripsi, subtotal, catatan, payment_details, do_rounddown=False, use_ppn=False, rounddown_limit=1000, output_folder='.'):
    """
    Args:
        subtotal (int): Total harga murni.
        do_rounddown (bool): Opsi pembulatan.
        use_ppn (bool): Opsi PPN 5%.
        output_folder (str): Folder penyimpanan.
    """
    pdf = PDF()
    pdf.set_auto_page_break(auto=True, margin=35) 
    pdf.add_page()
    
    # --- 1. INFO FAKTUR ---
    now = datetime.now()
    tgl_str = now.strftime("%d%m%Y")
    # Tambahkan timestamp detik agar nama file unik
    ts = int(now.timestamp())
    nomor_faktur = f"{tgl_str}{user_id}-{ts}" 
    
    tanggal_faktur = now.strftime("%d/%m/%Y")
    jatuh_tempo = (now + timedelta(days=30)).strftime("%d/%m/%Y")

    pdf.set_font('Arial', 'B', 12)
    pdf.cell(0, 6, f'Faktur: {nomor_faktur}', 0, 1, 'R')
    pdf.set_font('Arial', '', 10)
    pdf.cell(0, 5, f'{tanggal_faktur}', 0, 1, 'R')
    pdf.cell(0, 5, f'Jatuh Tempo: {jatuh_tempo}', 0, 1, 'R')
    pdf.ln(5)

    # --- 2. INFO KLIEN ---
    pdf.set_font('Arial', 'B', 11)
    pdf.cell(0, 5, 'Klien:', 0, 1, 'L')
    pdf.set_font('Arial', '', 11)
    pdf.cell(0, 5, f'{nama_klien}', 0, 1, 'L')
    pdf.cell(0, 5, f'{email_klien}', 0, 1, 'L')
    pdf.cell(0, 5, f'{no_hp}', 0, 1, 'L')
    pdf.ln(10)

    # --- 3. TABEL ITEM ---
    pdf.set_fill_color(245, 245, 245)
    pdf.set_font('Arial', 'B', 10)
    pdf.cell(90, 8, 'Deskripsi', 'B', 0, 'L', 1) 
    pdf.cell(30, 8, 'Qty', 'B', 0, 'C', 1)
    pdf.cell(35, 8, 'Harga', 'B', 0, 'R', 1)
    pdf.cell(35, 8, 'Total', 'B', 1, 'R', 1)

    pdf.set_font('Arial', '', 10)
    subtotal_str = format_currency(subtotal)
    
    # Layout Baris Item
    current_y = pdf.get_y()
    pdf.multi_cell(90, 10, deskripsi, 'B', 'L')
    last_y = pdf.get_y()
    
    # Pindah ke kolom kanan
    pdf.set_xy(100, current_y)
    pdf.cell(30, 10, '1', 'B', 0, 'C')
    pdf.cell(35, 10, subtotal_str, 'B', 0, 'R')
    pdf.cell(35, 10, subtotal_str, 'B', 1, 'R')
    pdf.set_y(max(last_y, pdf.get_y()))

    # --- 4. HITUNG TOTAL (PPN & ROUNDDOWN) ---
    ppn = subtotal * 0.05 if use_ppn else 0
    total_pre = subtotal + ppn
    
    if do_rounddown:
        grand_total = math.floor(total_pre / rounddown_limit) * rounddown_limit
    else:
        grand_total = total_pre

    # --- 5. TAMPILAN ANGKA ---
    pdf.ln(2)
    pdf.set_font('Arial', '', 10)
    
    # Subtotal
    pdf.cell(155, 6, 'Subtotal', 0, 0, 'R')
    pdf.cell(35, 6, subtotal_str, 0, 1, 'R')
    
    # PPN
    if use_ppn:
        pdf.cell(155, 6, 'PPN (5%)', 0, 0, 'R')
        pdf.cell(35, 6, format_currency(ppn), 0, 1, 'R')
    
    # Info Pembulatan (Opsional)
    if do_rounddown and (total_pre != grand_total):
        pdf.set_font('Arial', 'I', 8)
        pdf.cell(155, 6, f'(Pembulatan)', 0, 0, 'R')
        pdf.set_font('Arial', '', 10)
        pdf.cell(35, 6, format_currency(grand_total - total_pre), 0, 1, 'R')

    # Grand Total
    pdf.set_font('Arial', 'B', 11)
    pdf.cell(155, 8, 'Total Bayar', 'T', 0, 'R') 
    pdf.cell(35, 8, format_currency(grand_total), 'T', 1, 'R')
    pdf.ln(10)

    # --- 6. INFO FOOTER ---
    pdf.set_font('Arial', 'B', 10)
    pdf.cell(0, 5, 'Pembayaran:', 0, 1, 'L')
    pdf.set_font('Arial', '', 9)
    pdf.multi_cell(100, 4, payment_details)
    pdf.ln(3)
    
    pdf.set_font('Arial', 'B', 10)
    pdf.cell(0, 5, 'Catatan:', 0, 1, 'L')
    pdf.set_font('Arial', '', 9)
    pdf.multi_cell(100, 4, catatan)
    pdf.ln(5)
    
    # QRIS
    pdf.set_font('Arial', 'B', 10)
    pdf.cell(0, 5, 'SCAN DI SINI', 0, 1, 'L') 
    if os.path.exists('qris.jpg'):
        pdf.image('qris.jpg', w=35) 
    elif os.path.exists('qris.png'):
        pdf.image('qris.png', w=35)

    # --- SIMPAN FILE ---
    if not os.path.exists(output_folder) and output_folder != '.':
        os.makedirs(output_folder)

    filename = f"Faktur_{nomor_faktur}.pdf"
    full_path = os.path.join(output_folder, filename)
    
    pdf.output(full_path)
    return full_path